apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingassistantservice
  labels:
    app: shoppingassistantservice
spec:
  selector:
    matchLabels:
      app: shoppingassistantservice
  template:
    metadata:
      labels:
        app: shoppingassistantservice
    spec:
      serviceAccountName: shoppingassistantservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          image: shoppingassistantservice
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: GOOGLE_API_KEY
              value: GOOGLE_API_KEY_VAL
            - name: ALLOYDB_CLUSTER_NAME
              value: ALLOYDB_CLUSTER_NAME_VAL
            - name: ALLOYDB_INSTANCE_NAME
              value: ALLOYDB_INSTANCE_NAME_VAL
            - name: ALLOYDB_DATABASE_NAME
              value: ALLOYDB_DATABASE_NAME_VAL
            - name: ALLOYDB_TABLE_NAME
              value: ALLOYDB_TABLE_NAME_VAL
            - name: ALLOYDB_SECRET_NAME
              value: ALLOYDB_SECRET_NAME_VAL
            - name: PROJECT_ID
              value: PROJECT_ID_VAL
            - name: REGION
              value: REGION_VAL
            # Datadog LLM Observability (Agentless Mode)
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: api-key
            - name: DD_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: app-key
            - name: DD_SITE
              valueFrom:
                configMapKeyRef:
                  name: datadog-config
                  key: dd-site
            - name: DD_ENV
              valueFrom:
                configMapKeyRef:
                  name: datadog-config
                  key: dd-env
            - name: DD_SERVICE
              value: 'shoppingassistantservice'
            - name: DD_LLMOBS_ENABLED
              value: 'true'
            - name: DD_LLMOBS_AGENTLESS_ENABLED
              value: 'true'
            - name: DD_LLMOBS_ML_APP
              value: 'v-commerce-shopping-assistant'
            - name: DD_TRACE_ENABLED
              value: 'true'
            - name: DD_LOGS_INJECTION
              value: 'true'
            # Point to Datadog Agent running on the same node
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: '8126'
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
  labels:
    app: shoppingassistantservice
spec:
  type: ClusterIP
  selector:
    app: shoppingassistantservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shoppingassistantservice
  annotations:
    iam.gke.io/gcp-service-account: ALLOYDB_USER_GSA_ID
