apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: adservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: adservice
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: '9555'
            # Datadog APM Configuration
            - name: DD_SERVICE
              value: 'adservice'
            - name: DD_ENV
              value: 'hackathon'
            - name: DD_VERSION
              value: '1.0.0'
            - name: DD_TRACE_ENABLED
              value: 'true'
            - name: DD_AGENT_HOST
              value: 'datadog-agent'
            - name: DD_TRACE_AGENT_PORT
              value: '8126'
            - name: DD_LOGS_INJECTION
              value: 'true'
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
