apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-insights-service
  labels:
    app: observability-insights-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observability-insights-service
  template:
    metadata:
      labels:
        app: observability-insights-service
    spec:
      serviceAccountName: observability-insights-service
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: observability-insights-service
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: project_id
            - name: LOCATION
              value: "us-central1"
            - name: HTTP_PORT
              value: "8080"
            # Scheduling intervals
            - name: ERROR_PREDICTION_INTERVAL_MINUTES
              value: "5"
            - name: COST_ANALYSIS_INTERVAL_HOURS
              value: "1"
            - name: HEALTH_SUMMARY_INTERVAL_MINUTES
              value: "15"
            # Datadog credentials
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: api-key
            - name: DD_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: app-key
            - name: DD_SITE
              valueFrom:
                configMapKeyRef:
                  name: datadog-config
                  key: dd-site
            - name: DD_ENV
              valueFrom:
                configMapKeyRef:
                  name: datadog-config
                  key: dd-env
            - name: DD_SERVICE
              value: "observability-insights-service"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            # GCP credentials
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: observability-insights-service
  labels:
    app: observability-insights-service
spec:
  type: ClusterIP
  selector:
    app: observability-insights-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-insights-service
  annotations:
    iam.gke.io/gcp-service-account: insights-service@PROJECT_ID.iam.gserviceaccount.com
