apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    tags.datadoghq.com/env: 'hackathon'
    tags.datadoghq.com/service: 'paymentservice'
    tags.datadoghq.com/version: '1.0.0'
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
        tags.datadoghq.com/env: 'hackathon'
        tags.datadoghq.com/service: 'paymentservice'
        tags.datadoghq.com/version: '1.0.0'
      annotations:
        ad.datadoghq.com/server.logs: '[{"source": "nodejs", "service": "paymentservice"}]'
    spec:
      serviceAccountName: paymentservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: paymentservice
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: '50051'
            - name: DISABLE_PROFILER
              value: '1'
            # Datadog APM Configuration
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: '8126'
            - name: DD_DOGSTATSD_PORT
              value: '8125'
            - name: DD_LOGS_INJECTION
              value: 'true'
            - name: DD_RUNTIME_METRICS_ENABLED
              value: 'true'
            - name: DD_PROFILING_ENABLED
              value: 'true'
            - name: DD_TRACE_SAMPLE_RATE
              value: '1'
            # Agentless mode (fallback if no agent)
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: DD_API_KEY
                  optional: true
            - name: DD_SITE
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: DD_SITE
                  optional: true
          readinessProbe:
            grpc:
              port: 50051
          livenessProbe:
            grpc:
              port: 50051
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice
