apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-generation
  labels:
    app: video-generation
spec:
  selector:
    matchLabels:
      app: video-generation
  template:
    metadata:
      labels:
        app: video-generation
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: video_generation
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: 'productcatalogservice:3550'
            - name: FRONTEND_SERVICE_ADDR
              value: 'frontend:80'
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: video-generation-secrets
                  key: GEMINI_API_KEY
            - name: VEO_MODEL_ID
              value: 'veo-3.0-fast-generate-001'
            - name: PROJECT_ID
              value: 'v-commerce-480915'
            - name: LOCATION
              value: 'us-central1'
            # Datadog APM Configuration
            - name: DD_SERVICE
              value: 'video-generation'
            - name: DD_ENV
              value: 'hackathon'
            - name: DD_VERSION
              value: '1.0.0'
            - name: DD_TRACE_ENABLED
              value: 'true'
            - name: DD_AGENT_HOST
              value: 'datadog-agent'
            - name: DD_TRACE_AGENT_PORT
              value: '8126'
            - name: DD_LOGS_INJECTION
              value: 'true'
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 600
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 12
            httpGet:
              path: /health
              port: 8080
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: video-storage
              mountPath: /app/videos
      volumes:
        - name: video-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: video-generation
  labels:
    app: video-generation
spec:
  type: ClusterIP
  selector:
    app: video-generation
  ports:
    - name: http
      port: 8080
      targetPort: 8080
